import os
import json
import re
import requests
import sys

## CKAN Connection details

# URL to CKAN API 
CKAN_API='https://stelar.vsamtuc.top/api/3/action/'

# IMPORTANT! API_KEY must have been generated by a CKAN user with ADMIN privileges
# API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJBMjZEMHkzZXhvTzhMSEFMcHFra1ZQNlQ4R0M4UTNOVGF0dHc3OEczT2RrIiwiaWF0IjoxNzExODUxMTYwfQ.Gizn9cZY19miltcm9T4JEUxHD0KAcISKFtHUKgyXHrU"

API_KEY = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJqdGkiOiJIYzhlNE9MYTU5eGhQc0Y5Ymw1T3BlZkZ0YmxIU0FGeFlYYm9hRlVVdkljIiwiaWF0IjoxNzExODY5NTg0fQ.BqZn6V7hZNaPoVsyJTQ3ga1mj475wiNIgEJv5TYG8iM"

# Provide the API key required for requests regarding user management
admin_headers = { 'Authorization' : API_KEY, 'Content-Type' : 'application/json'}

# Provide the API key required for requests regarding user updates
# Syntax differs from the one used for creating users
adminx_headers = { "X-CKAN-API-Key" : API_KEY,  'Content-Type' : 'application/json'}

# Name or UUID internally used by CKAN for the organization where the publisher belongs to
OWNER_ORG = 'athenarc'


## Publish a dataset in the Catalog

# The metadata regarding a dataset specified in a dictionary:

dataset_metadata = {
    'title': 'Lakes of Greece published through CKAN API',
    'name': 'lakes-of-greece-via-api',
    'notes': 'This [spatial dataset](http://geodata.gov.gr/en/dataset/limnes-elladas) contains the lakes of Greece and its extracted profile.   \n **Original data** obtained from geodata.gov.gr',
    'tags': [{'name': 'Lakes'}, {'name': 'Greece'}, {'name': 'Hydrography'}, {'name': 'Inland waters'}],
    'private': 'false',
    'version':'0.1',
    'extras': [{'key': 'custom_tags', 'value': 'http://www.w3.org/ns/dcat#Dataset'}, 
               {'key': 'theme', 'value': 'Hydrography'}, 
               {'key': 'CRS', 'value': 'EPSG:2100'},
               {'key': 'spatial', 'value': '{"coordinates": [[[25.705543, 35.034625], [25.861189, 41.402938], [20.644119, 41.369031], [20.924371, 35.007623], [25.705543, 35.034625]]], "type": "Polygon"}'}
              ],
    'owner_org': 'athenarc' 
}
import json
print(json.dumps(dataset_metadata))

# Make a POST request to the CKAN API with the headers

response = requests.post(CKAN_API+'package_create', json=dataset_metadata, headers=adminx_headers)

print(response.json())
