"""Centralized help text for the stelarctl CLI.

The CLI uses Typer/Rich, so keeping command descriptions here avoids scattering
operator-facing wording across command handlers. Keep this file focused on what
an operator needs to know at the terminal: workflow order, generated files, and
safety boundaries.
"""

from __future__ import annotations

from textwrap import dedent

import typer

CONTEXT_SETTINGS = {"help_option_names": ["-h", "--help"]}


def show_help_on_no_args(ctx: typer.Context) -> None:
    """Print group help and exit successfully when no subcommand is selected."""
    if ctx.invoked_subcommand is None:
        typer.echo(ctx.get_help())
        raise typer.Exit()

ROOT_HELP = (
    "Prepare a STELAR KLMS lake deployment workspace before rendering or "
    "applying Kubernetes manifests with Tanka. stelarctl creates the workspace "
    "layout, resolves product specs into fullspecs, updates Tanka environment "
    "metadata, checks cluster prerequisites, and creates deployment secrets."
)
ROOT_EPILOG = dedent(
    """
    Typical workflow: run `init-lake workspace`, then `jb install`, then
    `init-lake environment`, then `product init-minimal` or your own product,
    then `product generate`, then `product init-manual-tls` if manual TLS is
    selected, then `init-lake cluster`, and finally `tk apply environments/<env>`.

    Main concepts: a workspace is the root with jsonnetfile.json, vendor/, and
    environments/; an environment is one Tanka entrypoint under environments/<env>;
    a product is the user-selected feature/configuration input; a fullspec is the
    generated, fully defaulted config consumed by Jsonnet.

    Safety boundary: stelarctl scaffolds files and creates missing Kubernetes
    Secrets. It does not run tk apply for you. Read-only preflight checks can be
    skipped with --skip-preflight when RBAC prevents inspection.
    """
).strip()

PRODUCT_HELP = (
    "Create and resolve KLMS product specifications. Use this group when you "
    "need a product YAML/JSON, a generated product_fullspec.json inside an "
    "environment, or the manual TLS input template required by cluster init."
)
PRODUCT_EPILOG = dedent(
    """
    Product flow: init-minimal creates a core-only product spec for a first
    deployment; generate validates a product and writes product.json plus
    product_fullspec.json; init-manual-tls writes the manual_tls.yaml template
    for manual HTTPS certificates.

    TLS rules: SCHEME=http must use ingress.tls no_tls and forces
    minio.INSECURE_MC_CLIENT=true. SCHEME=https must use cert_manager,
    manual_tls, or self_signed. init-minimal supports only http/no_tls and
    https/cert_manager.
    """
).strip()

INIT_MINIMAL_HELP = (
    "Interactively create a minimal product YAML for a core KLMS deployment. "
    "It selects required core components only, PVC-backed storage, nginx ingress, "
    "and no optional tools. This is the easiest starting point for a deployable "
    "lake product."
)
INIT_MINIMAL_EPILOG = dedent(
    """
    Prompts include namespace, root domain, subdomains, storage classes, SMTP
    values, and secret values unless --generate-secret-values is provided.

    TLS behavior: http selects no_tls and forces minio.INSECURE_MC_CLIENT=true;
    https selects cert_manager and asks for a ClusterIssuer name; manual_tls is
    not generated by this minimal flow, so use a custom product plus product
    init-manual-tls when you need manually supplied certificates.

    Secret handling: --generate-secret-values creates cryptographically random
    values and writes a sidecar *.secrets.yaml file. Store that file securely.
    """
).strip()

INIT_MANUAL_TLS_HELP = (
    "Write the manual_tls.yaml input template used by init-lake cluster when a "
    "product selects ingress.tls manual_tls. The file maps each public endpoint "
    "to a directory containing tls.crt and tls.key."
)
INIT_MANUAL_TLS_EPILOG = dedent(
    """
    Place the edited file at environments/<env>/manual_tls.yaml before running
    init-lake cluster. The YAML contains certificate directories only; Kubernetes
    Secret names come from product_fullspec.json ingress.manual_tls.

    Expected endpoint keys are primary, keycloak, minio_api, and registry. Each
    referenced directory must contain a matching PEM certificate/key pair named
    tls.crt and tls.key.
    """
).strip()

PRODUCT_GENERATE_HELP = (
    "Validate a product JSON/YAML file against the STELAR feature model and "
    "write the normalized product.json plus generated product_fullspec.json into "
    "an initialized environment."
)
PRODUCT_GENERATE_EPILOG = dedent(
    """
    Inputs: PRODUCT is the user-authored product spec; ENV is an initialized
    environment such as dev or environments/dev.

    Outputs: environments/<env>/product.json keeps the validated product input;
    environments/<env>/product_fullspec.json contains all feature-model defaults
    and is the config inventory consumed by Jsonnet.

    Validation highlights: http requires no_tls and minio.INSECURE_MC_CLIENT=true;
    https requires cert_manager, manual_tls, or self_signed; manual_tls requires
    PRIMARY_TLS_SECRET_NAME, KEYCLOAK_TLS_SECRET_NAME, MINIO_API_TLS_SECRET_NAME,
    and REGISTRY_TLS_SECRET_NAME.
    """
).strip()

INIT_LAKE_HELP = (
    "Initialize lake deployment state. Use this group to create the workspace "
    "root, create Tanka environment directories, and prepare cluster-specific "
    "metadata/secrets for an environment."
)
INIT_LAKE_EPILOG = dedent(
    """
    Required order: init-lake workspace, then jb install from the workspace root,
    then init-lake environment, then product generate, then init-lake cluster.
    The final Kubernetes apply is explicit: run tk apply environments/<env> after
    init-lake cluster succeeds.
    """
).strip()

INIT_LAKE_WORKSPACE_HELP = (
    "Create or update a deployment workspace root. The workspace contains "
    "jsonnetfile.json, vendor/ after jb install, and environments/ entries."
)
INIT_LAKE_WORKSPACE_EPILOG = dedent(
    """
    After this command, run jb install from the workspace root. Jsonnet Bundler
    downloads the vendored STELAR deployment library and its Jsonnet dependencies
    into vendor/.

    Existing jsonnetfile.json files are merged with the required dependency when
    possible. Use --force only when you intentionally want to rewrite it from the
    packaged template.
    """
).strip()

INIT_LAKE_ENVIRONMENT_HELP = (
    "Create one Tanka environment under environments/<env>. The environment is "
    "the deployable unit that later receives product.json, product_fullspec.json, "
    "spec.json metadata, and optional manual_tls.yaml."
)
INIT_LAKE_ENVIRONMENT_EPILOG = dedent(
    """
    This command expects jb install to have populated vendor/ because the Tanka
    main.jsonnet template is copied from the vendored STELAR deployment library.
    Existing main.jsonnet and spec.json files are preserved.
    """
).strip()

INIT_LAKE_CLUSTER_HELP = (
    "Prepare an initialized environment for Kubernetes. The command writes the "
    "active/selected kubectl context and namespace into spec.json, validates "
    "cluster prerequisites, and creates missing product/manual-TLS Secrets."
)
INIT_LAKE_CLUSTER_EPILOG = dedent(
    """
    Preflight checks verify namespace, storage classes, nginx ingress, and, when
    cert_manager TLS is selected, cert-manager plus the configured ClusterIssuer.

    RBAC behavior: if the Kubernetes user cannot perform a read-only check, the
    command stops and explains the missing access. Rerun with --skip-preflight
    only when you accept that cluster readiness will be discovered later by tk apply.

    Secret behavior: missing product secrets are created and existing secrets are
    left untouched. If product_fullspec.json selects manual_tls,
    environments/<env>/manual_tls.yaml must exist and point to valid tls.crt/tls.key
    pairs.

    HTTP behavior: HTTP deployments skip cert-manager checks and require MinIO
    insecure client mode in the fullspec.
    """
).strip()
