"""Centralized help text for the stelarctl CLI."""

from __future__ import annotations

import typer

CONTEXT_SETTINGS = {"help_option_names": ["-h", "--help"]}


def show_help_on_no_args(ctx: typer.Context) -> None:
    """Print group help and exit successfully when no subcommand is selected."""
    if ctx.invoked_subcommand is None:
        typer.echo(ctx.get_help())
        raise typer.Exit()

ROOT_HELP = (
    "Create STELAR deployment workspaces, product specs, generated fullspecs, "
    "and cluster bootstrap resources."
)
ROOT_EPILOG = (
    "Workflow: init-lake workspace -> init-lake environment -> "
    "product generate -> init-lake cluster. "
    "Use product init-minimal for a core-only product; use product "
    "init-manual-tls when a product selects manual_tls."
)

PRODUCT_HELP = (
    "Create product specs, resolve them into fullspecs, and prepare optional "
    "manual TLS input files."
)
PRODUCT_EPILOG = (
    "Minimal products are core-only. HTTP forces MinIO insecure mode. "
    "Manual TLS products require product_fullspec.json secret names plus "
    "environments/<env>/manual_tls.yaml endpoint directories."
)

INIT_MINIMAL_HELP = (
    "Interactively write a minimal product YAML. It selects required core "
    "components only, PVC storage, nginx ingress, and no optional components."
)
INIT_MINIMAL_EPILOG = (
    "TLS: http selects no_tls and forces minio.INSECURE_MC_CLIENT=true; "
    "https selects cert_manager and prompts for ClusterIssuer; manual_tls is "
    "not generated by this minimal flow. Secrets are prompted unless "
    "--generate-secret-values is used."
)

INIT_MANUAL_TLS_HELP = (
    "Write the packaged manual_tls.yaml template used by init-lake cluster "
    "when a product selects ingress.tls manual_tls."
)
INIT_MANUAL_TLS_EPILOG = (
    "Place the file at environments/<env>/manual_tls.yaml. Endpoint values "
    "point to directories containing tls.crt and tls.key. Secret names come "
    "from product_fullspec.json, not from manual_tls.yaml."
)

PRODUCT_GENERATE_HELP = (
    "Validate a product JSON/YAML file against the feature model and write "
    "product.json plus product_fullspec.json into an environment."
)
PRODUCT_GENERATE_EPILOG = (
    "Validation: http requires no_tls and minio.INSECURE_MC_CLIENT=true; "
    "https requires cert_manager, manual_tls, or self_signed; manual_tls "
    "requires four TLS secret-name attributes."
)

INIT_LAKE_HELP = (
    "Initialize deployable lake workspace state: workspace roots, environment "
    "directories, and cluster bootstrap resources."
)
INIT_LAKE_EPILOG = (
    "Run in order: workspace, environment, product generate, then cluster."
)

INIT_LAKE_WORKSPACE_HELP = (
    "Create a workspace root with jsonnetfile.json and the local lib directory."
)
INIT_LAKE_WORKSPACE_EPILOG = (
    "Use --force to rewrite jsonnetfile.json from the packaged template. "
    "Without --force, missing dependencies are merged into an existing file."
)

INIT_LAKE_ENVIRONMENT_HELP = (
    "Create an environment directory under environments/ and copy the packaged "
    "Tanka entrypoint template."
)
INIT_LAKE_ENVIRONMENT_EPILOG = (
    "The environment later receives product.json, product_fullspec.json, and "
    "cluster metadata before rendering/apply."
)

INIT_LAKE_CLUSTER_HELP = (
    "Populate spec.json from product data and kubectl context, run preflight "
    "checks, and create required Kubernetes Secrets."
)
INIT_LAKE_CLUSTER_EPILOG = (
    "Default preflight checks namespace, storage, ingress, and cert-manager "
    "when needed. --skip-preflight bypasses read-only checks only. "
    "manual_tls requires environments/<env>/manual_tls.yaml. HTTP skips "
    "cert-manager checks and requires MinIO insecure mode."
)
